# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'NodejsClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NodejsClient
  pod 'Alamofire', '~> 4.7.3'
  pod 'FoldingCell', '~> 3.1.2'
  pod 'SnapKit', '~> 4.0.0'
  pod 'SlideMenuControllerSwift'
  pod 'DynamicColor', '~> 4.0.2'
  pod 'Kingfisher'
  pod 'Toast-Swift', '~> 4.0.0'

  # Swift 版本声明
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if ['FoldingCell', 'SnapKit', 'SlideMenuControllerSwift', 'Kingfisher'].include? target.name
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '4.0'
                  config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
              end
              else
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '4.2'
                  config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
              end
          end
      end
  end
  
end
